version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
    restart: unless-stopped  
    environment:
      #dockker
      - WAIT_HOSTS:mysql:3306
    #those will be used by config.py and app.py, before changing it read them to understand
      - APP_SETTINGS=config.DevelopmentConfig  
    #the mysql url, we gonna parse it true os env
      - DATABASE_URL=mysql://root:1234@db:3306/telemedicina

  db:
    image: mysql:5.7
    restart: always
    ports:
      - "32000:3306"
    environment:
    # to check some mysql env : https://github.com/docker-library/docs/tree/master/mysql
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: hildermes
      MYSQL_PASSWORD: telemedicina
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
