version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: hildermes
      MYSQL_ROOT_PASSWORD: 1234

    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
